### ISSUE TITLE
I can't move

### ISSUE THREAD

**Issue by Zekrodiak** [sfDesat/Orion#1]
My character stays stuck in the same position. I can walk, run, jump...but stays in the same spot.

**Comment by syprate** [comment]
> My character stays stuck in the same position. I can walk, run, jump...but stays in the same spot.

I am not experiencing this issue, but I have a completely fresh install.

**Comment by sfDesat** [comment]
> My character stays stuck in the same position. I can walk, run, jump...but stays in the same spot.

What kind of mods are you using? It may be a compatibility issue.
Are you on the latest v0.1.0?
Could you send your LogOutput.log file?

**Comment by Zekrodiak** [comment]
I was using the latest version. v0.1.0
When I remove Orion it gets fixed.
These are my mods
![Screenshot 1](https://github.com/sfDesat/Orion/assets/152932408/2b1b4069-b9bd-4cad-83cc-bdaaf8013c61)
![Screenshot 2](https://github.com/sfDesat/Orion/assets/152932408/e04d4a1a-ed62-466d-bdde-21e64175f23d)

Where can I find LogOutput.log file?

**Comment by sfDesat** [comment]
Go to settings and click on Browse Profile Folder. (I use r2modman but it should be the same for thunderstore)
![image](https://github.com/sfDesat/Orion/assets/75356901/3d2c6fb3-bcd7-41d7-8b92-1980f80364ad)

Then click on BepInEx And it should be there at the bottom

**Comment by Zekrodiak** [comment]
Lol I use neither but it's probably a mod conflict. I'll find the issue quick.

**Comment by Zekrodiak** [comment]
Found the issue. Apparently your mod has a conflict with the "More emotes mod".
This is the mod...
https://thunderstore.io/c/lethal-company/p/Sligili/More_Emotes/

Would be awesome if you can fix this and make them compatible since "more emotes" is very cool to have, and it's very popular too.

**Comment by sfDesat** [comment]
I can't reproduce the issue can you send you LogOutput.log. It should be in \Steam\steamapps\common\Lethal Company\BepInEx

Hvae you tried reinstalling LethalExpansion and Orion? maybe its some old files.

**Comment by syprate** [comment]
> Found the issue. Apparently your mod has a conflict with the "More emotes mod". This is the mod... https://thunderstore.io/c/lethal-company/p/Sligili/More_Emotes/
> 
> Would be awesome if you can fix this and make them compatible since "more emotes" is very cool to have, and it's very popular too.

I had more emotes installed and enabled when testing and did not see this issue either. I'm wondering if it's a conflict with more emotes and a different mod. You could always create a profile with just more emotes, and Orion and test the compatability that way.

**Comment by Zekrodiak** [comment]
All my mods are up to date. 
If more emotes didn't worked for you then there must be another one conflicting.

Here's the log...
[LogOutput.log](https://github.com/sfDesat/Orion/files/13639106/LogOutput.log)

**Comment by sfDesat** [comment]
Have you made sure that all mods are up-to-date and if that doesn't work maybe reinstall all the mods (if you use thunderstore or r2modman, exporting the profile as a code. Then deleting the profile. Then using the code to install all the mods.)

**Comment by sfDesat** [comment]
This issue will be closed due to inactivity and unable to reproduce.

**Comment by ItsToshio** [comment]
This is a closed issue, but I ran into the exact same problem of being unable to move and found that the incompatibility is with LC_API (3.0.2). Removing LC_API fixed the movement problem and also fixed several other mod loading issues (Lethal Progression, HotbarPlus).

As far as I can tell, I have not had any problems with the Orion mod specifically, so the original issue was likely unrelated to this mod.

**Comment by syprate** [comment]
> This is a closed issue, but I ran into the exact same problem of being unable to move and found that the incompatibility is with LC_API (3.0.2). Removing LC_API fixed the movement problem and also fixed several other mod loading issues (Lethal Progression, HotbarPlus).
> 
> As far as I can tell, I have not had any problems with the Orion mod specifically, so the original issue was likely unrelated to this mod.

Several mods have issues with LC_API if you put bepinex and the mods that conflict higher in the load order then place LC_API lower in the load order this tends to fix that.
