### ISSUE TITLE
Game Crashes when trying to get on the planet

### ISSUE THREAD

**Issue by CLAPPINURCHEEKS1** [sfDesat/Orion#10]
Just tried to go and see if the monster problem was fixed and i couldn't even load into the moon the game just crashes, i tried to land 4 times and all 4 times it crashed

**Comment by sfDesat** [comment]
Hi, could you list the mods you were using and show you LogOutput.Log file

**Comment by Maskueradez** [comment]
It woks solo but crashes for friends in multiplayer. Crashes regardless of who hosts. Here is my profile code. 
018c7531-24f9-e867-0dcc-836c4fe6c29c

**Comment by CLAPPINURCHEEKS1** [comment]
> Hi, could you list the mods you were using and show you LogOutput.Log file
I don’t know if you will be able to see the photo but there is the log output and the mods I am using at the current moment. It worked for me today when I tried to land just took a minute to Load I am going to try it with a friend later when he gets on
![image](https://github.com/sfDesat/Orion/assets/153776847/c85aaee3-7acf-46c0-89e1-c0edf118d21f)

**Comment by CLAPPINURCHEEKS1** [comment]
> > Hi, could you list the mods you were using and show you LogOutput.Log file
> > I don’t know if you will be able to see the photo but there is the log output and the mods I am using at the current moment. It worked for me today when I tried to land just took a minute to Load I am going to try it with a friend later when he gets on
> > ![image](https://private-user-images.githubusercontent.com/153776847/291073348-c85aaee3-7acf-46c0-89e1-c0edf118d21f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MjkyNTQsIm5iZiI6MTcwMjgyODk1NCwicGF0aCI6Ii8xNTM3NzY4NDcvMjkxMDczMzQ4LWM4NWFhZWUzLTdhY2YtNDZjMC04OWUxLWMwZWRmMTE4ZDIxZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxN1QxNjAyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTBiZjJiOTIxODZmOGVhZDU1ZjZjZDU1N2U5NGQwOWZmYjgxYThmMzcxYzhiZmU2Y2U3NmNlNTM3NWJiYTg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vprwg_advyfNF5_1AQIU3baKTjhn_rIgDQB8lEVOH14)
[LogOutput.log](https://github.com/sfDesat/Orion/files/13696755/LogOutput.log)
here is the whole log if you need it

**Comment by CLAPPINURCHEEKS1** [comment]
> > > Hi, could you list the mods you were using and show you LogOutput.Log file
> > > I don’t know if you will be able to see the photo but there is the log output and the mods I am using at the current moment. It worked for me today when I tried to land just took a minute to Load I am going to try it with a friend later when he gets on
> > > ![image](https://private-user-images.githubusercontent.com/153776847/291073348-c85aaee3-7acf-46c0-89e1-c0edf118d21f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MjkyNTQsIm5iZiI6MTcwMjgyODk1NCwicGF0aCI6Ii8xNTM3NzY4NDcvMjkxMDczMzQ4LWM4NWFhZWUzLTdhY2YtNDZjMC04OWUxLWMwZWRmMTE4ZDIxZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxN1QxNjAyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTBiZjJiOTIxODZmOGVhZDU1ZjZjZDU1N2U5NGQwOWZmYjgxYThmMzcxYzhiZmU2Y2U3NmNlNTM3NWJiYTg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vprwg_advyfNF5_1AQIU3baKTjhn_rIgDQB8lEVOH14)
> > > [LogOutput.log](https://github.com/sfDesat/Orion/files/13696755/LogOutput.log)
> > > here is the whole log if you need it

also just went into the map and died again and i just wanted to let you know that it seems like its something with lethal expansion itself cause you still dont die when a snare flea drops on your head

**Comment by sfDesat** [comment]
The snare flea doesn't kill you when playing solo. I am still looking into your crash and having trouble reproducing the problem. Have you tried reinstalling your mods? You can find some more information [here](https://github.com/sfDesat/Orion/issues/11).

**Comment by Maskueradez** [comment]
Issues seem resolved. I was legit in the process of messaging with logoutput files and with a mod list as the update came out. The update fixes it. Next time though i will have logoutputs at the ready. I pinky promise. Thank you sfDeat <3

**Comment by CLAPPINURCHEEKS1** [comment]
> The snare flea doesn't kill you when playing solo. I am still looking into your crash and having trouble reproducing the problem. Have you tried reinstalling your mods? You can find some more information [here](https://github.com/sfDesat/Orion/issues/11).

i did try to reinstall my mods cause a little bit ago i had trouble with my version being 16485 a couple days ago when i tried to play with a friend and it was because some mods were not compatible with version 45 so i just deleted my whole profile on thunderstore and made a new one. My game has not yet crashed again so i do believe that the update fixed the problem that i was crashing into. Thank you :) I will continue to try it out and see if i find any bugs will let you know as soon as i do

**Comment by sfDesat** [comment]
Thats great to hear! I will now close this thread. If any new problems arise open up a new issue.
