### ISSUE TITLE
[LE] Invisible dropship / Purple sun

### ISSUE THREAD

**Issue by HamedAlmanthari** [sfDesat/Orion#12]
hi, i'm not sure if these bugs are caused by Orion or LE, but here are two screenshots i took to demonstrate the issues. one of them with HDcompany (first screenshot) and the other without. i thought the glitched sun would be because of HDcompany but it's not. idk if i have another mod that is conflicting with this mod but that wouldn't make sense, or would it? i ordered a pro flashlight and i couldn't hear the music from the loot drop but i noticed this light so i thought this might be the loot drop but it's invisible and i can't open it to get my loot. 
EDIT: the sun is also sometimes glitched in Watergate made by HolographicWings. also, the loot drop works in Watergate but it's a little bit bugged. it plays the music while it's coming on the way and it drops loot floating in the air. 
EDIT 2: that light you see in the screenshot is not the sun, it is the light which is on top of the loot drop, i think. it was floating in the air where it would tell me to press "e" to open.
![Screenshot 2023-12-19 20442722](https://github.com/sfDesat/Orion/assets/133137232/6d46534f-5b04-48f8-94a6-ebffff29a72f)
![Screenshot 2023-12-19 205603234](https://github.com/sfDesat/Orion/assets/133137232/c4456065-72e5-47cd-ac69-06286b6b505f)
and also i had another issue with my friend where his game would crash when we pull the lever to land the ship. my game doesn't crash maybe because i'm the host. i saw another issue similar to this and they said the fixed it somehow. i will let my friend reinstall his mods later when i play with him again and get back to you. i already reinstalled my mods. ty

**Comment by HamedAlmanthari** [comment]
Dependency string list

BepInEx-BepInExPack-5.4.2100
RickArg-Helmet_Cameras-2.1.5 (disabled)
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.6.3
malco-Lategame_Upgrades-2.6.5
Evaisa-LethalThings-0.7.1
Sligili-More_Emotes-1.2.2
FlipMods-LetMeLookDown-1.0.1
x753-Mimics-2.2.1
togglemybits-Strange_Objects-1.2.1
Midge-PushCompany-1.2.0
AllToasters-QuickRestart-1.2.0
2018-LC_API-2.2.0
RugbugRedfern-Skinwalkers-2.0.1
FlipMods-MoreBlood-1.0.2
xCeezy-LethalEscape-0.7.6 (disabled)
MonAmiral-PlayerDogModel-1.0.0 (disabled)
egeadam-MoreScreams-1.0.3 (disabled)
joe1359-LethalExtras-1.0.4 (disabled)
HolographicWings-LethalExpansion-1.2.16
sfDesat-Orion-0.5.5
MaxWasUnavailable-MoonOfTheDay-1.0.4
stormytuna-KindTeleporters-1.0.2
malco-Terminal_TP-1.0.1 (disabled)
CYW-DevysOQLMod-2.0.0
tinyhoot-ShipLoot-1.0.0
x753-More_Suits-1.4.1
EliteMasterEric-Coroner-1.4.2
notnotnotswipez-MoreCompany-1.7.2 (disabled)
Verity-TooManySuits-1.0.4
anormaltwig-LateCompany-1.0.6
Krayken-DynamicDeadline-1.2.2
2018-Brutal_Company_Reborn-1.1.0 (disabled)
2018-Brutal_Company-1.2.4 (disabled)
Nips-Brutal_Company_Plus-3.5.0 (disabled)
Sculas-BrutalCompanyAdditions-2.1.1 (disabled)
Blorb-WeatherMultipliers-1.0.0
Stoneman-LethalProgression-1.3.2 (disabled)
Clementinise-QuickTerminalRestart-1.0.3 (disabled)
KoderTeh-Boombox_Controller-1.1.1 (disabled)
HomelessGinger-MaskedEnemyOverhaul-2.1.0
ManiaBania-1000_Quota_Stare-1.0.0
Stoners-SpiderManSuitV2-1.2.0
TeamClark-ShirtlessSuit-1.0.0
Flamango-OmniMan_Base_Suits-1.0.0
Drakorle-MoreItems-1.0.1 (disabled)
AllToasters-SpectateEnemies-1.5.0
VZP_Mods-BetterLethality-1.0.1 (disabled)
kyxino-LethalUtilities-1.2.8 (disabled)
happyfrosty-FrostySuits-1.1.4
MythicFrog-FrogSkins-1.0.11
Norman-GlowStickSuits-1.0.3
Sligili-HDLethalCompany-1.5.6 (disabled)
Hexnet111-SuitSaver-1.1.2
alexanderjoe-LC_Symphony-1.2.0
Mom_Llama-Lethal_Company_Enhancer-0.1.8 (disabled)
Owen3H-IntroTweaks-1.2.2
MegaPiggy-BuyableShotgun-1.0.0
MegaPiggy-BuyableShotgunShells-1.0.1
NotAtomicBomb-TerminalApi-1.4.0 (disabled)
NotAtomicBomb-Terminal_Clock-1.0.5 (disabled)
anormaltwig-TerminalExtras-1.0.1
kRYstall9-FastSwitchPlayerViewInRadar-1.3.1
Badham_Mods-SCPFoundationDungeon-1.1.1
CapyCat-Solos_Bodycams-1.0.4
Aavild-NewTerminal-1.4.0
TwinDimensionalProductions-CoilHeadStare-1.0.3
IntegrityChaos-Diversity-1.0.5

**Comment by HamedAlmanthari** [comment]
this is a screenshot of watergate. everything works mostly right other than music while the loot drop is landing and the floating loot and the occasional glitched sun texture.
![image](https://github.com/sfDesat/Orion/assets/133137232/abf231c6-d6bb-4528-b410-9f4cbc4ad963)

**Comment by sfDesat** [comment]
The glitched sun is a problem with LethalExpansion and I will have to wait for it to update to fix it. I will however look into the droppod issue, but this may also be bound to LethalExpansion.

**Comment by HamedAlmanthari** [comment]
alright ty. also, about the crashing issue, my friend and i reinstalled our mods and we managed to land on the moon once without a crash. but then while we were inside the facility, as soon as my friend died by thumper, his game crashed. then, when we tried to land on the moon again, his game started crashing again.

**Comment by sfDesat** [comment]
A patch has been rolled out
