### ISSUE TITLE
[LE] It can rain inside the facility

### ISSUE THREAD

**Issue by Wesley-wasnietavailabledusdanmaarzo** [sfDesat/Orion#13]
I was outside, I don't know if that matters but when a masked enemy kills/claims you or any player, the game seems to crash.
I was not using any other mods than the required dependencies.
And I am using the latest version.

**Comment by sfDesat** [comment]
I will look into the issue. Do you know if this happens with other enemies?

**Comment by sfDesat** [comment]
Could you let me know if it still happens on the latest patch 0.6.0?

**Comment by Wesley-wasnietavailabledusdanmaarzo** [comment]
Sorry for the late reply but the masked didn't crash my game on 0.6.0.
Dying in general doesn't crash the game either.
I have noticed however that on rainy days, it rains inside the building.
Which is.. actually pretty cool but I'm not sure if it's intended.

**Comment by sfDesat** [comment]
Good to hear that its fixed. And the rain is not an intended feature.

**Comment by Wesley-wasnietavailabledusdanmaarzo** [comment]
Ah, I feel like you already know this but the inside rain is also a thing on Aquatis.
And also since the discord seems to not be working I'll ask here:
Is there a reason why the models of the buildings for instance look really undetailed?
Just curious, love your work though!

**Comment by sfDesat** [comment]
A patch has been rolled out for Orion and Aquatis. The reason the buildings look so undetailed is because Lethal Company compresses the textures. Which makes it look low-res.
