### ISSUE TITLE
link to discord doesnt work

### ISSUE THREAD

**Issue by willboyz92nd** [sfDesat/Orion#14]
Sorry for opening an issue here but I didnt know any other way to reach out about it.
following the link posted on both this mod and your other moons mod page https://discord.com/channels/1169792572382773318/1188025007759179857
results in a screen like this 
![image](https://github.com/sfDesat/Orion/assets/70662672/aa7b1fd2-0438-43e8-8f1d-f2a6de2485a4)

**Comment by sfDesat** [comment]
That's weird, maybe you need to join the server first. The link on the thunderstore page goes to a thread on the Unofficial Lethal Company Community. Here is a link https://discord.gg/nYcQFEpXfU
