### ISSUE TITLE
The terminal does not display the moon.

### ISSUE THREAD

**Issue by zz2108828** [sfDesat/Orion#15]
![image](https://github.com/sfDesat/Orion/assets/13402394/85bcd49f-2899-4334-9393-51be50cdbe4a)

**Comment by RoryDotGG** [comment]
I have the same issue here on v47
![image](https://github.com/sfDesat/Orion/assets/13355761/36cb6e4b-48a4-4297-a5d7-a46a4842b076)

**Comment by sfDesat** [comment]
It seems Lethal Expansion is not installed correctly and is not showing up.

**Comment by panicthescaredycat** [comment]
> It seems Lethal Expansion is not installed correctly and is not showing up.

I've uninstalled and reinstalled both the moons and Lethal Expansion, still doesn't show up for me.

**Comment by sfDesat** [comment]
Then there is most likely a mod compatibility problem. I recommend first trying to launch the  game with just Orion and Lethal Expansion and then add mods 1 (or more) by 1.

**Comment by DarkoPendragon** [comment]
Just noting, found [this](https://github.com/IAmBatby/LethalLevelLoader/issues/4) while trying to figure out which mod was causing this. LethalExpansion and LethalLevelLoader are not compatible. Using [Lethal Expansion Core](https://thunderstore.io/c/lethal-company/p/jockie/LethalExpansionCore/) allowed the moons to load somewhat properly though.
![image](https://github.com/sfDesat/Orion/assets/28911975/76b08dc9-153d-4c2c-8cac-dbc5ccf09c13)

**Comment by sfDesat** [comment]
This is indeed the best fix until Lethal Expansion rolls out a patch. Just download both Lethal Expansion and Lethal Expansion Core.

**Comment by ZestyBlaze** [comment]
It seems to be an issue with LethalLevelLoader. If it's loaded alongside Lethal Expansion then it won't load any of the moons added via LethalExpansion because they modify the same thing

**Comment by sfDesat** [comment]
If you use LethalLevelLoader it is currently not compatible with Lethal Expansion. To fix this just add LethalExpansionCore for now

**Comment by sfDesat** [comment]
It has now been ported to LethalLevelLoader
