### ISSUE TITLE
[LE] Modded dungeons

### ISSUE THREAD

**Issue by CarpetKraken** [sfDesat/Orion#16]
Probably obvious somewhere, but when tinkering with the SCP foundation mod config, for modded moons it requires the name on the moon level. Wasn't able to find it anywhere, the basic "orionLevel" wasn't successful.

**Comment by sfDesat** [comment]
I have not tested this mod with SCP Foundation. I'm pretty sure it would be called orion, but there is currently no official support for modded dungeons. This feature is in the works, but will have to come via Lethal Expansion. Link to the thread is [here](https://github.com/HolographicWings/LethalSDK-Unity-Project/issues/38). I will look further into this issue

**Comment by sfDesat** [comment]
I am seeing people talking about the following internal names that worked for them: 13 Kast, 43 Orion, 112 Aquatis, 102 Wateridge, E Gypt, Ever Green Forest, Secret Labs

**Comment by CarpetKraken** [comment]
Thanks! I'll give them a shot

*edit* Yep, "43 Orion" worked perfectly fine.

**Comment by sfDesat** [comment]
Orion has been ported to LLL and now "Orion" will work as well
