### ISSUE TITLE
Interior seems to be getting affected by the outside

### ISSUE THREAD

**Issue by LordOfTheHobos** [sfDesat/Orion#17]
The inside of the mansion seemed to have full visibility on the radar, everything could be seen very clearly, despite the lighting not actually being present and during stormy weather lightning was striking on the inside. I have not checked any other weather conditions yet. I'm not sure if this is intentional, but the mod page was not clear if it was on purpose so I figured I'd report it.

**Comment by sfDesat** [comment]
Could you expand on "The inside of the mansion seemed to have full visibility on the radar"? The lightning striking inside is a known bug that has to be fixed through Lethal Expansion.

**Comment by LordOfTheHobos** [comment]
Everything inside seems entirely lit up on the radar, as thought there was lighting everywhere. People inside didn't notice anything though. I haven't checked recently to see if its still an issue.

**Comment by sfDesat** [comment]
Could you send a screenshot. I don't fully understand what you mean.
