### ISSUE TITLE
Request, not issue

### ISSUE THREAD

**Issue by Aleksandermyr** [sfDesat/Orion#19]
Could you add the amount of fireexits to your map in description? It seems like LethalExpansion doesnt work with interiors if theres multiple fire exits on multiplayer.

**Comment by sfDesat** [comment]
There are 2 fire exits on the map. What kind of issues are you having? I have pushed out an update that temporarily disables the second fire exit, because i heard more people talk about this issue.

**Comment by NoahBPeterson** [comment]
> There are 2 fire exits on the map. What kind of issues are you having? I have pushed out an update that temporarily disables the second fire exit, because i heard more people talk about this issue.

I'm having an issue where the second fire exit can't be used. When trying to use it, it says something about the other side being blocked in an in-game popup. I have the same issue on Aquatis.

**Comment by sfDesat** [comment]
Should be fixed and if not, it is because the fire exit is physically blocked by bookshelfs inside
