### ISSUE TITLE
Ship Will not return to orbit.

### ISSUE THREAD

**Issue by syprate** [sfDesat/Orion#2]
When leaving any of the maps the ship will not return to orbit.

**Comment by sfDesat** [comment]
> When leaving any of the maps the ship will not return to orbit.

What kind of mods are you using? It may be a compatibility issue.
Are you on the latest v0.1.0?
Could you send your LogOutput.log file?

**Comment by syprate** [comment]
> > When leaving any of the maps the ship will not return to orbit.
> 
> What kind of mods are you using? It may be a compatibility issue. Are you on the latest v0.1.0? Could you send your LogOutput.log file?

I created a separate profile in ThunderStore with only Orion and its dependencies installed and enabled. These were freshly installed with no prior mods and the Mod Cache was cleaned prior to installation. The issue seems to appear after landing once on the moon then returning to orbit. Landing and returning to orbit a second time causes the ship to never fully return to orbit. The furthest it gets is to through the XP screen.

[LogOutput.log](https://github.com/sfDesat/Orion/files/13639522/LogOutput.log)

**Comment by syprate** [comment]
For my modded profile this happens on Water the first time returning to orbit.  here is the log provided.

[LogOutput.log](https://github.com/sfDesat/Orion/files/13639553/LogOutput.log)

**Comment by sfDesat** [comment]
A patch has been pushed out. [0.2.1]

**Comment by syprate** [comment]
> A patch has been pushed out. [0.2.1]

Confirmed to have corrected the issue even with my Modded profile.
