### ISSUE TITLE
Random Stutter / Fps Drop

### ISSUE THREAD

**Issue by DHStyle541** [sfDesat/Orion#22]
Hi, Nice Moons.
but This is moon Random Stutter and Fps drop
i hope u fix that. maybe because NavMesh?

**Comment by sfDesat** [comment]
it is not supposed to have random stutters, can you send your modlist?

**Comment by DHStyle541** [comment]
my modpack:
![image](https://github.com/sfDesat/Orion/assets/154591650/9bb6b8ce-a56d-4730-ab1f-b12e4f847456)

but basicly my friend also stutter and fps drop when landing Orion
and another my friend get like this is ( he can't move always white screen )

![image](https://github.com/sfDesat/Orion/assets/154591650/5528e486-d958-487d-af96-1c11e5c4d752)

only on Orion. 
And yeah orion get error log console
![image](https://github.com/sfDesat/Orion/assets/154591650/97ba9a85-3f40-46d4-8636-e61538fd83d2)


Log: [LogOutput.log](https://github.com/sfDesat/Orion/files/13965227/LogOutput.log)

**Comment by sfDesat** [comment]
The error log (Error RuntimeNavmeshBuilder: ) is fine. Its a bug that should only lead to a slight increase in loading time, but not game breaking. In your LogOutput.log I see a lot of LethalRichPresence. I don't know what it does, but it might be worth trying to see if disabling it might stop the problem? If that doesn't work try disabling some other mods (exmaples: Performancebooster_v1 or LethalPresents).

**Comment by DHStyle541** [comment]
but every wanna landing on Orion, waiting for crew so long.
and only my friend is get bug White screen like that picture ( but other custom moons is fine like Aquatis )

because i setting Read is "ALL" on WriteonLog, that why u can see so many LRP ( only discord rich pressence )
about Performancebooster already deleted. LethalPresents is Gacha like RNG what got Enemy? or Present

and 1 more Sandworm can Scan, and you can falling on the map if you stuck on ship
![20240119010428_1](https://github.com/sfDesat/Orion/assets/154591650/f187c219-abec-40e5-babe-d9f96ae286e0)

**Comment by sfDesat** [comment]
Long loading bug and performance has improved. I am closing this
