### ISSUE TITLE
Lethal Level Loader update breaks Orion's Moon Listing and Cost

### ISSUE THREAD

**Issue by Sourceshard** [sfDesat/Orion#23]
Lethal Level Loader intercepts moons loaded with LethalExpansion and LethalExpansionCore and displays them on the in-game moon Catalogue.

As such Orion does not display or load properly. I believe it is possibly suffering from issues #2 and 3.
I am unaware of whether you can fix this on your end to make it compatible but I wanted to bring it to your attention.

LLL Known Issues (As of 1.1.0.4)

-Mods that skip the initial LAN or Online scene will cause LLL to break by skipping it’s code

-LethalExpansion moons will be 0 route price due to issues with LethalExpansion breaking when SelectableLevel.levelID’s are modified 

-Lethal Expansion moons with uncommon characters in their planet name will likely break the game as LethalExpansion does not sanitise names when setting SelectableLevel asset names and LLL does not validate these names when parsing the automatic configuration system

-Saving and loading a save where a Custom Moon was the last active level will break the game due to an oversight regarding the levelID saved to the savefile via ES3

-Issues regarding routing to moons with similar names and/or spaces in the name are known

<img width="1280" alt="image" src="https://github.com/sfDesat/Orion/assets/37197624/906bc70a-ab42-4ecc-b2ef-e18b6af99a97">

**Comment by sfDesat** [comment]
Thank you for putting the problems into a list. I think most of the issues have to be fixed through LLL.  The 0 moon cost is indeed an issue and I have added a custom config file for the Explorations modpack. I think you need to reinstall the modpack to get it (and delete LethalLevelLoader config). I will do some more digging and post it if I find some more information or a fix.

**Comment by sfDesat** [comment]
This should be fixed now that Orion has ported to LLL
