### ISSUE TITLE
Can't go to a modded planet ( Orion specifically )

### ISSUE THREAD

**Issue by CongoBB** [sfDesat/Orion#25]
When we try to go to Orion, we get infinite loading and infinite same error in console, can't open doors and etc, have to restart after.
modlist - 018dfb31-28e3-62f9-59b3-7d8e59acc8b3
logs
[LogOutput.log](https://github.com/sfDesat/Orion/files/14496586/LogOutput.log)

**Comment by sfDesat** [comment]
This should be fixed, when LethalLevelLoader gets updated.
