### ISSUE TITLE
Drop Pod will not deploy on any of the new moons.

### ISSUE THREAD

**Issue by syprate** [sfDesat/Orion#3]
As the title states once landing on any of the moons and purchasing items the drop pod does not get deployed. If you attempt to return to orbit (which is currently broken), the terminal states items are in transit.

**Comment by sfDesat** [comment]
Yes, this is indeed a problem and it will be fixed later on. It does not work right now.

**Comment by sfDesat** [comment]
An update has been rolled out

**Comment by syprate** [comment]
You're awesome. keep up the good work.
