### ISSUE TITLE
Dependent on LethalExpansion?

### ISSUE THREAD

**Issue by Kayden21** [sfDesat/Orion#4]
Hi this is not necessarily an issue with your mod itself but I was wondering if this mod will stay dependent on lethal expansion? I am very interested in a new moon mod but I feel lethal expansion adds extra stuff that is really not necessary when all I want is to download one thing. Seems a shame that a new moon mod has to be locked behind a different mod with forced extra content.

**Comment by xamionex** [comment]
Agreed, It's no issue in my case since I use LE but not sure why they made LE the dependency when [LethalExpansionSDK](https://thunderstore.io/c/lethal-company/p/HolographicWings/LethalSDK/) is a thing

**Comment by sfDesat** [comment]
Orion uses some essential systems from LethalExpansion and wont work without it. LethalSDK is only used to design the new moons. Personaly I don't think it is an issue as LethalExpansion doesn't change much about the base game, but I understand that some people won't like it.

**Comment by xamionex** [comment]
> Orion uses some essential systems from LethalExpansion

I just realized LESDK has LE as a dependency, so it wouldn't make a difference no matter what you do x)

**Comment by HolographicWings** [comment]
@Kayden21 @xamionex 
Hello, i concider what you are telling
Lethal Expansion don't force any new content, by default everything is vanilla, except a missing light added in space and a maze added to the company building as a test, i will remove it

If you don't want the new scraps, test moon and the wateridge moon, you can remove the templatemod.lem, i plan to make it independent, but LE is still highly wip and need an huge amount of testings so i must let it for now

**Comment by HolographicWings** [comment]
@Kayden21  @xamionex 
Hello, i concider what you are telling
The SDK is only a tool to create content without adding any copyrighted code from Zeekerss.
The Expansion read and implement the content from the SDK into the game.

Lethal Expansion don't force any new setting, by default every setting in the mod menu is vanilla, as new content, theres a missing light added in space and a maze added to the company building as a test that i will remove.

If you don't want the new scraps, test moon and the wateridge moon, you can remove the templatemod.lem, i plan to make it independent, but LE is still highly wip and need an huge amount of testings so i must let it for now
But Orion use theses scraps so will not load without the template, sfDesat can remove the scraps from the spawnlist of Orion to make it not depending of the template
I will hide the testmoon from the terminal in the next major update.

**Comment by Kayden21** [comment]
@HolographicWings I assumed I could remove wateridge and test moon by removing the .lem but when I do then Orion does not appear but I probably just did it wrong. The mod is good I just think any new content should be easily configurable like all the other options.

**Comment by HolographicWings** [comment]
As I said, orion use the scraps from the template, so depends of it

**Comment by HolographicWings** [comment]
> Hi this is not necessarily an issue with your mod itself but I was wondering if this mod will stay dependent on lethal expansion? I am very interested in a new moon mod but I feel lethal expansion adds extra stuff that is really not necessary when all I want is to download one thing. Seems a shame that a new moon mod has to be locked behind a different mod with forced extra content.

As I said, orion use the scraps from the template, so depends of it

**Comment by sfDesat** [comment]
Orion has now been ported to LLL
