### ISSUE TITLE
[Crash] Compatibility issue with RickArg-Helmet_Cameras

### ISSUE THREAD

**Issue by otDan** [sfDesat/Orion#6]
I may play with more mods than most (?) this is the mod list we play as a group:

```
- 2018-LC_API-2.1.2
- BepInEx-BepInExPack-5.4.2100
- notnotnotswipez-MoreCompany-1.7.1
- x753-More_Suits-1.3.3
- MikeMediaStudios-MikesTweaks-1.9.1
- Sligili-HDLethalCompany-1.5.3
- FlipMods-LetMeLookDown-1.0.1
- tinyhoot-ShipLoot-1.0.0
- Suskitech-AlwaysHearActiveWalkies-1.4.2
- Drakorle-MoreItems-1.0.1
- RickArg-Helmet_Cameras-2.1.5
- Evaisa-HookGenPatcher-0.0.5
- Evaisa-LethalLib-0.6.2
- malco-Lategame_Upgrades-2.5.1
- tinyhoot-ShipLobby-1.0.2
- joe1359-LethalExtras-1.0.4
- MaxWasUnavailable-ScrollInverter-1.0.0
- Evaisa-LethalThings-0.7.1
- sunnobunno-ScalingStartCredits-1.0.1
- TeamClark-RustHazmatSuit-1.0.0
- EladNLG-EladsHUD-1.1.0
- monkes_mods-JumpDelayPatch-1.0.1
- BatTeam-LethalFashion-1.0.4
- togglemybits-Strange_Objects-1.2.1
- Stoneman-LethalProgression-1.3.1
- x753-Mimics-2.0.0
- klepticat-JetpackWarning-2.1.0
- JoshFoRs-Spectators-1.1.1
- Sligili-More_Emotes-1.1.3
- extraes-LethalLoudnessMeter-1.0.1
- steven4547466-CommandHandler-1.0.0
- steven4547466-YoutubeBoombox-1.4.0
- RugbugRedfern-Skinwalkers-2.0.1
- boxofbiscuits97-QuotaRollover-2.0.0
- no00ob-LCSoundTool-1.3.2
- AriDev-JesterFree-2.0.0
- EliteMasterEric-Coroner-1.1.0
- Ryokune-LethalParrying-1.0.2
- xCeezy-LethalEscape-0.7.6
- Flof-MemeSoundboard-1.1.1
- HolographicWings-LethalExpansion-1.1.9
- sfDesat-Orion-0.3.2
- Rune580-LethalCompany_InputUtils-0.3.0
- TwinDimensionalProductions-DanceOff-1.0.6
```

The crash happens even when just playing alone

**Comment by otDan** [comment]
If you wanna try the profile directly: 018c5ee0-65b4-3c12-cd41-9990419d2fba

**Comment by sfDesat** [comment]
The profile you send me works for me. Could you send me your LogOutput.Log? And have you tried reinstalling your own profile?

**Comment by otDan** [comment]
have you actually tried it? anyone in our group can't host and I have tried already multiple times to go to the moon
![image](https://github.com/sfDesat/Orion/assets/59731738/9b7a2765-10bb-4b89-942d-c03c66f76a3d)
https://hastebin.skyra.pw/cimugixero.yaml

**Comment by sfDesat** [comment]
I used your code and it worked for me. Try uninstalling your profile and reinstalling using the profile code. I think one of the installed mods may be corrupted. And are you on the latest version of the game V45?

**Comment by sfDesat** [comment]
I think there is some sort of conflict with LC_API. I am still working on the problem.

**Comment by xamionex** [comment]
> I think there is some sort of conflict with LC_API. I am still working on the problem.

Insta crash when loading in with [LC_BetterTeleport](https://thunderstore.io/c/lethal-company/p/JT/LC_Better_Teleport/)

This is my modlist
```
DISABLED: LC_Better_Teleport by JT
3rdPerson by Verity
BepInExPack by BepInEx
BetterItemScan by PopleZoo
BetterLadders by e3s1
BiggeryBattery by alexanderjoe
BrotherPigs_Suits by BrotherPig
BuyableShotgun by MegaPiggy
BuyableShotgunShells by MegaPiggy
CrossHair by CTNOriginals
DanceTools by dancemoon
darmuhsTerminalStuff by darmuh
DissonanceLagFix by linkoid
DoorFix by itsmeowdev
EladsHUD by EladNLG
FlashlightToggle by Renegades
FOV_Adjust by Rozebud
FriendlyFirelessCompany by RogerFK_TEAM
HDLethalCompany by Sligili
HookGenPatcher by Evaisa
HotbarPlus by FlipMods
HullBreaker_Company by Venterok
IntroTweaks by Owen3H
JetpackHandling by Invertigo
JetpackWarning by klepticat
JumpDelayPatch by monkes_mods
LandmineFix by TheBeeTeam
Lategame_Upgrades by malco
LCItemValue by DeathGOD7
LethalExpansion by HolographicWings
LethalLib by Evaisa
LethalLoudnessMeter by extraes
LethalRadiation by gamehog44
LethalThings by Evaisa
LetMeLookDown by FlipMods
Mimics by x753
More_Emotes by Sligili
More_Suits by x753
NiceChat by taffyko
Orion by sfDesat
Permanent_Ladder by Silvercore
QuotaRollover by boxofbiscuits97
SellTracker by NutNutty
ShopkeeperNoWait by Sant5050
SlimeTamingFix by EliteMasterEric
Solos_Bodycams by CapyCat
Solos_Ring_Compass by CapyCat
SuitSaver by Hexnet111
Terminal_History by NotAtomicBomb
TerminalApi by NotAtomicBomb
TermSpeak by KodiCraft
TooManySuits by Verity
Touchscreen by TheDeadSnake
TZPReworkedHealing by Hotoni
VoiceHUD by 5Bit
WalkieUse by Renegades
WeatherMultipliers by Blorb
```
Hope it helps
Also, I think with LC_API when I had it, it didn't crash, it just never got past Random Seed generation text

**Comment by sfDesat** [comment]
A patch has been rolled out

**Comment by otDan** [comment]
still crashes

**Comment by xamionex** [comment]
Can confirm, [MoreCompany](https://thunderstore.io/c/lethal-company/p/notnotnotswipez/MoreCompany/) seems to cause it now

Modlist which works for me as of Orion 0.4.1:
```
Disabled:
inacraft_cosmetics_megapack
MoreCompany

BetterSpraycans by boxofbiscuits97
LethalCompany_InputUtils by Rune580
Forest_Giant_Motionsense by TanmanG
BetterStamina by FlipMods
ShopkeeperNoWait by Sant5050
3rdPerson by Verity
TermSpeak by KodiCraft
BuyableShotgun by MegaPiggy
BuyableShotgunShells by MegaPiggy
LCItemValue by DeathGOD7
Lethal_Company_Overhaul by Rushki
DissonanceLagFix by linkoid
Orion by sfDesat
DanceTools by dancemoon
LandmineFix by TheBeeTeam
NiceChat by taffyko
LethalLoudnessMeter by extraes
BrotherPigs_Suits by BrotherPig
CrossHair by CTNOriginals
BetterItemScan by PopleZoo
Touchscreen by TheDeadSnake
LethalRadiation by gamehog44
darmuhsTerminalStuff by darmuh
FOV_Adjust by Rozebud
Terminal_History by NotAtomicBomb
EladsHUD by EladNLG
DoorFix by itsmeowdev
SellTracker by NutNutty
SlimeTamingFix by EliteMasterEric
TooManySuits by Verity
LethalExpansion by HolographicWings
QuotaRollover by boxofbiscuits97
TerminalApi by NotAtomicBomb
Permanent_Ladder by Silvercore
Mimics by x753
JetpackWarning by klepticat
BetterLadders by e3s1
Lategame_Upgrades by malco
HullBreaker_Company by Venterok
FlashlightToggle by Renegades
WalkieUse by Renegades
HotbarPlus by FlipMods
More_Emotes by Sligili
SuitSaver by Hexnet111
WeatherMultipliers by Blorb
IntroTweaks by Owen3H
LethalThings by Evaisa
HDLethalCompany by Sligili
Solos_Bodycams by CapyCat
TZPReworkedHealing by Hotoni
LethalLib by Evaisa
HookGenPatcher by Evaisa
BiggeryBattery by alexanderjoe
JumpDelayPatch by monkes_mods
FriendlyFirelessCompany by RogerFK_TEAM
More_Suits by x753
Solos_Ring_Compass by CapyCat
LetMeLookDown by FlipMods
VoiceHUD by 5Bit
BepInExPack by BepInEx
```

**Comment by xamionex** [comment]
@sfDesat Can you look into this? I wish MC separated it's cosmetics part into another mod honestly :/
I'm guessing it probably has something to do with added players

**Comment by xamionex** [comment]
Checking up, [RickArg's HelmetCameras](https://thunderstore.io/c/lethal-company/p/RickArg/Helmet_Cameras/) crashes it too

Mod List:
```
Orion by sfDesat
LethalExpansion by HolographicWings
IntroTweaks by Owen3H
Helmet_Cameras by RickArg
BepInExPack by BepInEx
```

Further update as of Orion v0.5.0
MoreCompany crashes it _**when paired with HDLethalCompany**_

Upon further testing, HDLethalCompany and MoreCompany crash it when HDLC's Resolution Scale Value is >= 1.7 the game crashes upon loading, if it's <= 1.6 it works.

**Comment by xamionex** [comment]
Further update as of Orion v0.5.0 MoreCompany no longer crashes it, could've also been an incompatibility issue in my modpack.

**Comment by xamionex** [comment]
I Hope this info helps @sfDesat 
Tested minimally cause I really like your map!

**Comment by xamionex** [comment]
Upon further testing, HDLethalCompany and MoreCompany crash it when HDLethalCompany's Resolution Scale Value is set to above 1.6 the game crashes upon loading

**Comment by sfDesat** [comment]
It's great to hear that you like it and I will look further into the issue

**Comment by otDan** [comment]
still an issue, which mod is incompatible? have not been able to play once with this mod

**Comment by xamionex** [comment]
> still an issue, which mod is incompatible? have not been able to play once with this mod

Swap out RickArg's helmet cameras for [this](https://thunderstore.io/c/lethal-company/p/CapyCat/Solos_Bodycams/)

In HDLethalCompany's config change the resolution to 1.6

These are only workarounds for now, I've found that solos cams do load but don't work on the moon

And a bigger issue is that if you're the host with even 1 other person, the game lags a lot on custom moons, not sure if this is Orion or LethalExpansion issue

**Comment by sfDesat** [comment]
A patch has been rolled out
