### ISSUE TITLE
Bees and other outside entities can spawn inside the complex on Orion

### ISSUE THREAD

**Issue by joebama27** [sfDesat/Orion#7]
![image](https://github.com/sfDesat/Orion/assets/153679589/fed77d5a-2a49-4f0c-bb6b-f8e302e011b4)
i have not tested it on wateridge but i assume it doesn't happen there since i played on it last night and it was fine

**Comment by sfDesat** [comment]
There seems to be a problem with the navmesh. This will be fixed in the next update.

**Comment by sfDesat** [comment]
A patch has been rolled out.
