### ISSUE TITLE
Game Crashes when you Die

### ISSUE THREAD

**Issue by CLAPPINURCHEEKS1** [sfDesat/Orion#8]
Hi i was just playing your most recent update and i like that you added more monsters although it is a bit laggy right now im sure that will get better. I had a snare flea jump on my head and it didnt kill me only got me to critical and then hopped off my head and got back on the roof after that my game got really laggy, soon after that i encountered 4 loot bugs and a thumper and chose to die, when i died the game was frozen for a second when it said life support offline and then the game crashed. Just trying to relay some stuff i really like the mod and will continue to try it every time you update it:)

**Comment by sfDesat** [comment]
A patch has been rolled out. Let me know if you run into the issue again.
