### ISSUE TITLE
[LE] Quicksand from rainy weather is invisible

### ISSUE THREAD

**Issue by joebama27** [sfDesat/Orion#9]

**Comment by HiiJustin** [comment]
still happening, and on any day where the Quick sand is al over the place., it makes the game impossible

**Comment by sfDesat** [comment]
This is indeed still a known bug, but a solution has to come via Lethal Expansion.

**Comment by HiiJustin** [comment]
Oh :o how ? I'm not aware

**Comment by sfDesat** [comment]
Quicksand has been fixed in the latest version 2.0
